### ISSUE TITLE
Need persistent simple log of assigner runs

### ISSUE THREAD

**Issue by claudijd** [mozilla/infosec-risk-management-bugzilla#14]
Currently, we run the assigner code every 10 min and it does it's work, but I only persist job logs for the last 5 jobs or we'll just be burning up disk with these types of logs.

I was thinking maybe adding a persistent log where we only log changes that the script made.  This will give us accountability and easy access to information we need to go back and verify what the script did.

**Comment by gdestuynder** [comment]
where would the persistent log go, syslog?

**Comment by claudijd** [comment]
Syslog is fine, I would think, just wanted a place to look in case some thing happens that we don't expect

**Comment by gdestuynder** [comment]
@claudijd currently it goes to `stderr`
if we change the target to default to syslog, this would work, right?
