### ISSUE TITLE
Pickle Queues are not overwriting when config assigment change

### ISSUE THREAD

**Issue by claudijd** [mozilla/infosec-risk-management-bugzilla#26]
When we edit the config file to reflect new rotation participants, the resulting pickle queues are not being rotated.

We removed kang, but he's still in the pickle queue.

**Comment by claudijd** [comment]
I believe this is due to a logic flaw in this https://github.com/mozilla/infosec-risk-management-bugzilla/blob/master/assigner.py#L200

-> if set(assign_list) != set(assign_hash):
(Pdb) assign_list
['jclaudius@mozilla.com', 'culucenk@mozilla.com', 'gdestuynder@mozilla.com']
(Pdb) assign_hash
['gdestuynder@mozilla.com', 'jclaudius@mozilla.com', 'culucenk@mozilla.com']

**Comment by gdestuynder** [comment]
```
Traceback (most recent call last):
  File "./assigner.py", line 271, in <module>
    main()
  File "./assigner.py", line 267, in main
    autocasa(bapi, capi, config['bugzilla'], config['casa'], args.dry_run)
  File "./assigner.py", line 157, in autocasa
    elif (delegator_id != casa_status['decidingApprover']['id']):
TypeError: 'NoneType' object is not subscriptable
Build step 'Execute shell' marked build as failure
Sending e-mails to: jclaudius@mozilla.com gdestuynder@mozilla.com culucenk@mozilla.com
Finished: FAILURE
```

**Comment by gdestuynder** [comment]
i think i know now.. `assignee_hash` is supposedly a known order but cfg.get isnt
except the ordering (`assignee_hash=blah[:]`) doesnt work and doesnt need to, because `set` will order.

**Comment by gdestuynder** [comment]
that means we can probably drop all instances of `assignee_hash`
