### ISSUE TITLE
Deploy in pentest-master

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/infosec-risk-management-bugzilla#3]
And disable in eis-automation

**Comment by claudijd** [comment]
Got a stub job here, which will run both VA and RRA auto-assignment:

https://pentest-master.private.scl3.mozilla.com/job/RRA%20and%20VA%20auto-assigner/

It's probably most helpful if we solve for https://github.com/mozilla/infosec-risk-management-bugzilla/issues/4 and then add service specific config either in this repo.

**Comment by claudijd** [comment]
My intent would be have this job perform two commands, like so, every 2min or so...

assigner.py --config service_configs/vulnerability_assessment.yml
assigner.py --config service_configs/rapid_risk_assessment.yml

I will take care of making sure the BMO API is passed in as an environment variable allowing those configs to remain public.

**Comment by claudijd** [comment]
This is fixed.
