### ISSUE TITLE
RRA/VA doesn't log actions taken to STDOUT anymore

### ISSUE THREAD

**Issue by claudijd** [mozilla/infosec-risk-management-bugzilla#39]
since we've converted to module based called, the RRA/VA rotation still works, but doesn't log the actions.  We should ensure that logging returns to stdout, as it's helpful debug when something happens and we want to figure it out.

**Comment by gdestuynder** [comment]
this is a change that was made on your request :D 
you need `-d` to have msgs on stdout, else it only goes to syslog
