### ISSUE TITLE
Switch to a services strategy hierarchy that allows dynamic reading of services from the config

### ISSUE THREAD

**Issue by claudijd** [mozilla/infosec-risk-management-bugzilla#7]
Current state:

    rra:
        product: "Enterprise Information Security"
        component: "Rapid Risk Analysis"
        ...
    va:
        product: "Enterprise Information Security"
        component: "Rapid Risk Analysis"
        ...

Proposed state:

     services:
        - product: "Enterprise Information Security"
           component: "Rapid Risk Analysis"
           ...
        - product: "Enterprise Information Security"
           component: "Rapid Risk Analysis"
           ...

The reason I think this helps us is to make the parsing of services dynamic and not require editing of the assign.py.  It's a minor impact item, but it seems like a stronger pattern.

**Comment by gdestuynder** [comment]
sure is :)
